name: Run RSpec and integration tests

on: [push] 

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Install Bundler
        run: gem install bundler

      - name: Install project dependencies
        run: bundle install

      - name: Run RSpec tests
        run: bundle exec rspec
